spring.profiles.active: local
#spring.profiles.active: ${ENV:dev}

spring.application.name: rtomde
spring.main.banner-mode: log
server:
  port: 8080
  servlet.context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  environment: dev
