# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "1.0"

services:

  mysql:
    image: bitnami/mysql:8.0
    container_name: rtomde-mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: rtomde
      MYSQL_PASSWORD: rtomde
      MYSQL_DATABASE: rtomde
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MARIADB_CHARACTER_SET: utf8mb4
    volumes:
      - mysql:/bitnami/mysql
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - rtomde

  apollo:
    image: apolloconfig/apollo-configservice:1.8.1
    container_name: rtomde-apollo
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: rtomde-apollo
      SPRING_DATASOURCE_PASSWORD: rtomde-apollo
    volumes:
      - apollo:/apolloconfig/apollo-configservice
    restart: unless-stopped
    networks:
      - rtomde

networks:
  rtomde:
    driver: bridge

volumes:
  mysql:
  apollo: