spring:
  profiles.active: local
  application.name: rtomde
  main.banner-mode: log

logging.config: classpath:log4j2-spring.xml

platform.mybatis:
  environment: dev
  metadata-location: classpath:metadata-config.xml
  checkMetadataLocation: true
  applicationLocations: classpath:data_center-config.xml, boss_board-config.xml