spring.profiles.active: local
#spring.profiles.active: ${ENV:dev}

spring.application.name: rtomde
spring.main.banner-mode: log
server:
  port: 8080
  servlet.context-path: /${spring.application.name}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 20
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        logger: com.mysql.cj.log.Slf4JLogger
        logSlowQueries: true
        dumpQueriesOnException: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
