spring.profiles.active: local
#spring.profiles.active: ${ENV:dev}

spring.application.name: rtomde
spring.main.banner-mode: log
server:
  port: 8080
  servlet.context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

platform.mybatis:
  environment: dev
  metadata-location: classpath:metadata-config.xml
  checkMetadataLocation: true
  applicationLocations: classpath:application-config.xml

