spring:
  profiles.active: "@profile.active@"
  application.name: rtomde
  main.banner-mode: log

logging.config: classpath:log4j2-spring.xml

server:
  port: 8080
  servlet.context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

platform.mybatis:
  environment: dev
  metadata-location: classpath:metadata-config.xml
  checkMetadataLocation: true
  applicationLocations: classpath:data_center-config.xml, boss_board-config.xml

