spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rtomde?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123
    hikari.dataSourceProperties:
      logger: com.mysql.cj.log.Slf4JLogger
      logSlowQueries: true
      profileSQL: true
      dumpQueriesOnException: true