spring:
  datasource:
    url: jdbc:mysql://test-xc-dev.mysql.rds.aliyuncs.com:3331/data_service?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: test_xc_dev
    password: x!c@_d#ev$xcD_SdeAvM
    hikari.dataSourceProperties:
      logger: com.mysql.cj.log.Slf4JLogger
      logSlowQueries: true
      profileSQL: true
      dumpQueriesOnException: true