name: Check Code Style

on:
  push:
    paths-ignore: [ '**/*.md', '**/*.drawio' ]
  pull_request:
    paths-ignore: [ '**/*.md', '**/*.drawio' ]

jobs:
  Checkstyle:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodule: true
      - name: Check Style
        uses: nikitasavinov/checkstyle-action@master
        with:
          level: warning
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          checkstyle_config: ./buildtools/maven/checkstyle.xml
          workdir: ./